# Generated by Django 4.2.30 on 2026-07-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Movie', 'Movie'), ('Series', 'Series')], max_length=20)),
                ('genre', models.CharField(default='Action', max_length=100)),
                ('release_date', models.DateField()),
                ('year', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('duration', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('banner', models.ImageField(upload_to='banner/')),
                ('poster', models.ImageField(upload_to='poster/')),
                ('featured', models.BooleanField(default=False)),
                ('trending', models.BooleanField(default=False)),
                ('recent', models.BooleanField(default=False)),
                ('continue_watch', models.BooleanField(default=False)),
                ('trailer', models.URLField(blank=True)),
            ],
        ),
    ]
